apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - quizmon-worker.sops.yaml
  - quizmon-cloudflare.sops.yaml
  - quizmon-migration.sops.yaml
  - quizmon-sync-source.sops.yaml
  - quizmon-sync-storage.sops.yaml
  - runtime.yaml
