apiVersion: v1
kind: Secret
metadata:
    namespace: quizmon
    name: quizmon-migration
stringData:
    migration-connection.json: ENC[AES256_GCM,data:gbeMMnOd4SlIipwCWSpkyruTWdXyNZPYZXbzNm6bcMpG8ui1JA7g48Zn5MnDhM5EhUoQfdWXFEUyD2fJS+UPAarCHP9Ac4SMyZSPZd3zPsZeiyA0Ui30ZIKhGBwAWA8bgu67QT1Dm3Rg/fZYhcZ2ZYOKDXDqwEK/RMt/i8W1PaAfgZIodGosv9cgsTwjzsQ=,iv:UYg+vqPW5SGmDlwWRcEmXi7rIq28APX/16RjUh7yewc=,tag:Uph2xQ9t2X66tWtsfPgAcA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDJDM2Y5ZyBBZ0dRMHpD
            ZHJiZWZPNlNhbmF2djdHMTk2QzkreHZTbUlxelVCSUx0UkVkTQpxTXU5NEp2MmlE
            QklOd3pvaEdhZXNNbEJ5QmFvei9JMTBXRFlRUi8yeUdvCi0tLSArQ29mWWxqSTFw
            K1cwUURYTFRGRVEvRDRMRHQ5NXFZVDBNR2lYN2UrV2M4Cig9HJMkvjujSIV6t+JI
            h51a4BL7AHj9V1PmTAOiclMD646RrMXLWm2VTblZCb79JaG61IiXUYYj2ZMJqpru
            Q98=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qghympnz70sye3tx2a9yvudmmnvrq3ms7yd3gns8wz76r7k46hx0upwcu33
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDUyTHkxZyBBdVJrZTlL
            dktJWHJPUEI2YWlTQnJlcGV0MUtndllVckxscXpheU9oSmZoMQpPZExPN3BJTXNF
            RlZybmVSSWVKZHo0ZVhGR2M0OFhWckVNeUxUQmJ6UktjCi0tLSAyNmlWS1ZpMDJu
            T0xYblYzUENiVW4xTjlKTEt4VkFPZzFUaG4rZWxSY0VFCr3ZgyfWfR/1AzfspeuC
            uLIQ9I23lcDeGLO5guWUUIvB4uW1ourmtbSvInUmtHNn3u5ISYgQ9KtAKwOuC9A4
            Koc=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qvcujpaxamuraf4neev9xcxgj40e5x54n5a8kz0xvg3fpcnl6p48xsgkyg4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNUtyT3pQamdncXpLcGFh
            ZVp3YUUwRWN0cXZkVk8wT3FCLzRUcWVWM1JvCnBNNUlVZHJTeXVoc1c0VUwrZW5O
            QmJWOG9vMVZNbzBhWGlsdnFmdHN5dmcKLS0tIGpaaHQ2VWdzQnNxWVhETzNVUHE0
            bmFDMjFIWUJIdS9GSVBjSnR2YTJmcm8KMDqx9mgL1QflCwfU31jtQDrBDiB3NLYh
            WNJGOZ3WbRJrzUqENKzhiz+ZT9LL5L9EtPENuF0JqPMT1If3vYiJVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhztnm2nhdpcwsuv8uz6ss05tdx4jyfhm22dltu9l4u4fu8v3a4qs5asa7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T08:13:40Z"
    mac: ENC[AES256_GCM,data:BfEnhnoKAGMjV7pZzTj9HDXEDBKJF4u6FJ8MKBRAP0qlzWN5En7hF8x7B6nF/W8W5FQe+WYfskmUpzLbaLM6aM6RSVAUvm63yfCZncZWPnzvsvgd+GUPmFbUo503w+FyOu5HFRvxOIolL67QYlfUsd1ypmNKo9nkTonvmRTvDB8=,iv:p9VIAPL48dt74PywTbnSsoc4cu0dlSQFDjQZ3psztg8=,tag:wpMZskb2/XwAlMsDcvIy0g==,type:str]
    version: 3.13.3
