apiVersion: v1
kind: Secret
metadata:
    namespace: quizmon
    name: quizmon-migration-next
stringData:
    migration-connection.json: ENC[AES256_GCM,data:DRyzyPCakLeIXVZj3YO1fk5grjCfKUe/Mo/WKuE7c6HUJ3sldUXpZYikmDl67CWirrck8b2Arzv6htKUQ5ouQPT8eN9KLSwlyT+C3nS8TByBExXrSryxYoPwg4McXdO0Xzrsgn7lmTfmekaE4y5wHHBxW0nISYVHBRzrJnk87CNdwkDvHQfxF/0gIBPu3lALKdTJGfkNjdXmQiKxPoNxFA==,iv:MJh9yYz4FAx19rwEMHghpCFszPLvUqAzpFjo4iegiAI=,tag:/0gKvgKcKsHGPRb2p63p8A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDJDM2Y5ZyBBeXFtdkJY
            R2Y3RDZqM2UxdkRmRGFJbk0ycVRwMXNaNlZ0U01ZS1gxaVdIRgpZd2VMaStKOEN6
            azJ6WVNHalB2VGFrUDI2dkFZWkhEV3FZWGdDcWhWaWZvCi0tLSBvZkJPSllEM3pY
            a1NlZm42M0xHOGpIaUp0SDBWU2xFZ0p2RXUzeXV5M2tZCqLcR2fSKFFfLNKdZ0b8
            37n08OUG43Wnbde3w1+Z3V6WPtd0CKvGGAHWJkp5lSfaqCUKhSn5YCYiOcys3UGn
            OpU=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qghympnz70sye3tx2a9yvudmmnvrq3ms7yd3gns8wz76r7k46hx0upwcu33
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDUyTHkxZyBBaVlnYXQ1
            U2FyMGdCMzN5VjlMU2RmbGw5Y2xQcjkydzNORFl0bEczRHR5UgpRVXRHc0pmdXRm
            cWh1TnZROTFvd1NzdzlFVCs2ZVF6NDg3dCtFTmZlK0JzCi0tLSBGTlo2dEEvczd6
            SmlaTEtXR1ZSZnhxVUl3aDRpdXlBNkIwZFl3ekRZakRrCma/6CbUOvgzvIxW4Qt/
            cdvAyUuAnkJ+1Vk5J8Jk7fqpjL1VCnfW1jOGHR7rA5f+P7NATobYnkYHEhsGjnFk
            4OE=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qvcujpaxamuraf4neev9xcxgj40e5x54n5a8kz0xvg3fpcnl6p48xsgkyg4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQStDQU5uNWw2a053Z21R
            RlFtQ2MyMGdHeENaWDJISkFSQi9rYTJFbUdjCm0xcm05M29PREQwMDk3QzZjcWNX
            WUFSWGtGUnkybllhOUJTdkgxTU5Xc2MKLS0tIG1GMHVlY3drQVBiN0dkSUd4dzg4
            bytnSnREZDBEVEhxVDVMdmxjblAvejAKK8EyM7IXGx+whiF6hVxkO7KOYSrppIly
            +qsqRtZ609x0kTIMjWxcXZfH4zE6aqGt3nATq1A+RrLdfoovfOHACQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhztnm2nhdpcwsuv8uz6ss05tdx4jyfhm22dltu9l4u4fu8v3a4qs5asa7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T23:46:48Z"
    mac: ENC[AES256_GCM,data:g/5akN6PsMyw28il53MloTrsJa0e2lNSWhDyF87Kg07d95mfrS64aJC+7HZNF99v14QGI+Kn4FaEA7KvgSdv9f7hYmr0JtAkYpBVKbIWL5YUItCtipuNqgAk2nFemMG6JTzOgqwvEgMmX1cPipJH4UYkc3EiLyq0TJHRNN/ITGM=,iv:2UeXwA1c+YwhdCzBVDG+lfBAxr3zSK7ggtWw+LpRyQY=,tag:C8uHHLJmsYwOpMyzzOH+0w==,type:str]
    version: 3.13.3
