apiVersion: v1
kind: Secret
metadata:
    namespace: quizmon
    name: quizmon-sync-storage-next
stringData:
    uri: ENC[AES256_GCM,data:nXoHoqdUz9kKQJBD65gb+2twDLfVQYbwuKsyq9IK533YFS1k1LiehJxXF8tZDeqKv7MTk3u7qsg+ZnLMls42Wxj4GeBxvN6Yb2OXaj/D/2MdeO8QeQaUlS8DRQQPV3BFPSIj1GrKoJGQD3izZ95d1Va1PPsdDpFMMUasLTcdEF7M2w50QEesefA/eoI=,iv:0Cph0Q19PzFmGTL5ejNFeDbXfmNpYomeoeEWtwDKzIw=,tag:iFNuy8Cn/K8MIdisdFrPyg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDJDM2Y5ZyBBc0RPMk1s
            Z1Vkb0wxUTNMTFNvUm5BWmk4ci9Ecnprd0w0cXdrNUFmYXVsUQp4N2xTTkQzMXFr
            NHlwVmVVVnVDdVBuT2ZEQUZjRks0UjF2eFFXMDI2OXJBCi0tLSBkQ3hXbmJpbmVl
            VnFTK3hUQVM4eTNCK2R2OW5GZTFLclVvZEZsOW4vZit3CnPKOc/WlPdqLneF3UR+
            hyDNH9JN7TOCTmBp/RANawsec/4xV/rvOS4s3WxdoMXUlpFDGL3uhoH3TtVfXnxI
            IBI=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qghympnz70sye3tx2a9yvudmmnvrq3ms7yd3gns8wz76r7k46hx0upwcu33
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDUyTHkxZyBBdkdJTlpO
            NHpQREZQTjZqQmllRGFwei9JSU9CVzdjK21CSHV3T3hiZUNTUgp4eFRQRGExVW9Y
            ekxEeE9IcHR2VEJuYXRFbXdxSDZxY29TWGo2R1l3RVVJCi0tLSBhZU9mTzZHc0R3
            WWh2UVJIVDhnZ2hZS0pMU2hzaDNNc2ZIdWRqZkxRdkJNCoqkXNgNwlT85yNrD4q6
            Ic4R3wQb1sWWfY41ZgoQHGDj/lhkkwR7Yr6yGyGbq8aFDk8Ub2eBjb+LhwNZlO1Q
            myE=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qvcujpaxamuraf4neev9xcxgj40e5x54n5a8kz0xvg3fpcnl6p48xsgkyg4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRXN1OWVaM0ZQNVM1dTVN
            YjBycXdvR0RMYmtHZExBbVZuQU5tQVhXQ3lRClg5RUhNWmt4YWd0dnpHaHdmK0l1
            OUE4RmVKT3BjcEhMUDlIc0oyS0RTY2MKLS0tIEZmN1lKTkV0L3NRQ3FvcXBGeXhj
            dFBhZm03S2oyc3AzMTN1b2hBQllCZFUKzkPqV9o1iStXL1hvt8UFmG85+gcCFIRV
            sfSEU7ETlnnvHgP2PX8k1ozm0KFd0YneJ6F/klnQhxsGh+5K7ZMBSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhztnm2nhdpcwsuv8uz6ss05tdx4jyfhm22dltu9l4u4fu8v3a4qs5asa7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T23:46:49Z"
    mac: ENC[AES256_GCM,data:+F2qanFOIXN+oz8m+H2bSF2SSOLDGwiEUAOqQmdSuBhTrycXz0irF1soQqoEZ/liOgKwImRwNfHE9uV6pqKcwa6Q0EDIxnRUMWCge/n2MhnIzFelw8UJDaoDkv639NsV2t9KGFHgT7RRDVbbXK7BeBmqOMppOYni1H+tgpVQMN8=,iv:iiCPCQPzW7xAR1NWaOLabwikXl2WJNEuCaQ6epPudEY=,tag:6Tp+pQfwew/Ic+tb/XrqUg==,type:str]
    version: 3.13.3
