apiVersion: v1
kind: Secret
metadata:
    namespace: quizmon
    name: quizmon-sync-source-next
stringData:
    uri: ENC[AES256_GCM,data:nU1RupHEEJU2UeYIb0p6id2WI5Py3qZpWefca3xdFkv3sJTSavmmBr+Oqn3DWMlTVUEAPMv44664wOe8EtYZ0tqPosuTiyGXhUs5FcyeClW8cKU41KtOn8kwaUvTb0W61fPEfojqU3MWOeofsyIHspmcjfblzZGXeNzFT1Jdov+q9TfK3zivQJY=,iv:xHFK2Rad1MtgRv0MyYkeTdG+ZeOvj1/lGYLG5hkyYSI=,tag:IpFbD/pV+gXWNtZckCNVLw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDJDM2Y5ZyBBdnM4SVVI
            NVlWMnVxZkQza1R1bzB2SVRaWjRKU1MwRXB3TUZaMWxEK1I3UQo3N3dQYnU1TUJS
            dlhrS1BoNTdYbmVvUEFNVVg0MFYyNjFySTh3czlNVm5NCi0tLSBZMFRvUGE2aUNH
            bFNMYmNBQVhsa0RFU0x6OWxGM09nZjBJai9vczhoTlNnCuuwghEiK47iPHBGSndV
            OXoDYOTGktqLbaEIB0jkdwlOv/dN1nxHQxgfwDZvuC0soR1b8nJnar1p8nFwOYcQ
            xbg=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qghympnz70sye3tx2a9yvudmmnvrq3ms7yd3gns8wz76r7k46hx0upwcu33
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDUyTHkxZyBBcHZFYmVj
            WVZPRlZlTGpkcUVHM1ZsSUZOaGRwR0lWZmtYazFOZUVKdFlyTQpOOGRRdWZQUGhD
            WnVicytGbzBoWUZxeGdUejBLS2xqVGY1NnIrTjA3ZG5vCi0tLSAzVWxLUk4rZ1NN
            YUZyR1R5a2lGT0w4b0hoUXloRTBkZ3ZtM1R0YW9OWlU0Co/h79/Tw3EMWF43u35Q
            u7hvWJQgPNpSST4ZkBCNbUsCA4wRLCRfj95r1bhBS4rWa/n4hHFVajL2Gek9J40+
            3xw=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qvcujpaxamuraf4neev9xcxgj40e5x54n5a8kz0xvg3fpcnl6p48xsgkyg4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXM3lSRjdTUDA0NFpRYUpB
            TzRjMFI0T2lLV0lZOS9pYTI2WmVJbGpIYVdBCk4rc0FtK2ltZlJFZTYreTFpbmdG
            TEUxVW1PVXV6L0ppU25vRXFKZUk1STQKLS0tIDAvTGV0d0l4czljVnVzZk14T3ho
            djM4WHJtbW05Ym9NTkRyVGt1WVhuOEkKONstrKoOz65cDueUAVrVmjjffvtFn+1r
            rsACermH4FKRZ+SmXe9vlEHkO6Fsz474pUCBa+YWGws9zKddMoUGQQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhztnm2nhdpcwsuv8uz6ss05tdx4jyfhm22dltu9l4u4fu8v3a4qs5asa7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T23:46:49Z"
    mac: ENC[AES256_GCM,data:/LfdzuTK3yDeHRY+eaJsWVmIFvvOgxvyhFyKfHP6n7vQYFVEHEFzcE6XoA8ysOUML5WeoRdWqKSDKCc2/WJarS2zO+z4/QjkfkjYUZnBJ1vyEeVi0x7SYV0rJt/K2qB9ndF88VwK24pjKeZ1J28KV3wvHtrSIGOqoS3LfZgDWhg=,iv:iA652HvmRaqsw1jhU64iSjGPSa2xj5N+brGt89uvA08=,tag:8Zh9yVXMaHWWuiCfkb/GnQ==,type:str]
    version: 3.13.3
