apiVersion: v1
kind: ConfigMap
metadata:
  namespace: quizmon
  name: quizmon-runtime
  labels:
    reconcile.fluxcd.io/watch: Enabled
data:
  values.yaml: |
    runtimeConfig:
      hyperdriveId: a682435a618046e1a141d3cfb595cc4d
    inputs:
      migrationConnection:
        name: quizmon-migration-next
        key: migration-connection.json
        revision: 96b19a3eaac65ccc3108cf5a9b0b3c7973ee881ff19948ccb53bc0cf0e85df65
    powersync:
      sourceSecret:
        name: quizmon-sync-source-next
        key: uri
        revision: 96b19a3eaac65ccc3108cf5a9b0b3c7973ee881ff19948ccb53bc0cf0e85df65
      storageSecret:
        name: quizmon-sync-storage-next
        key: uri
        revision: 96b19a3eaac65ccc3108cf5a9b0b3c7973ee881ff19948ccb53bc0cf0e85df65
