storage:
  type: sqlite
  path: /data/data.db

ui:
  title: raveh.dev status
  header: raveh.dev

endpoints:
  - name: apex
    group: public
    url: https://raveh.dev
    interval: 60s
    conditions:
      - "[STATUS] < 500"
      - "[RESPONSE_TIME] < 2000"

  - name: status page (self)
    group: public
    url: https://status.raveh.dev
    interval: 60s
    conditions:
      - "[STATUS] == 200"

  - name: komodo core
    group: platform
    url: http://host.docker.internal:9120/
    interval: 60s
    conditions:
      - "[STATUS] == 200"

  - name: traefik
    group: platform
    url: http://traefik:80/
    interval: 60s
    conditions:
      - "[STATUS] == 404"
