apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: quizmon
  namespace: quizmon
spec:
  interval: 5m
  url: https://github.com/itay-raveh/quizmon.git
  ref:
    branch: main
  ignore: |
    /*
    !/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: quizmon
  namespace: quizmon
spec:
  interval: 5m
  releaseName: online
  timeout: 10m
  chart:
    spec:
      chart: ./charts/quizmon
      sourceRef:
        kind: GitRepository
        name: quizmon
      reconcileStrategy: Revision
  install:
    remediation:
      retries: 0
  upgrade:
    remediation:
      retries: 0
  valuesFrom:
    - kind: ConfigMap
      name: quizmon-runtime
      valuesKey: values.yaml
  values:
    releaseImage:
      repository: ghcr.io/itay-raveh/quizmon/release
      digest: sha256:71f85988dfd97afe93abc9752a50d4b8ae1c2ed23fc3d5a542ebbd3a5c557a76 # {"$imagepolicy": "flux-system:quizmon:digest"}
    runtimeConfig:
      workerName: quizmon
      origin: https://quizmon.raveh.dev
      sync:
        endpoint: https://quizmon-sync.raveh.dev
        audience: quizmon
      mailFrom: noreply@raveh.dev
      authRateLimitNamespace: "1011"
      apiRateLimitNamespace: "1012"
    powersync:
      enabled: true
