---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wanderbound-app-data
  namespace: wanderbound
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 40Gi
