apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: wanderbound-chart
  namespace: wanderbound
spec:
  interval: 5m
  url: oci://ghcr.io/itay-raveh/charts/wanderbound
  ref:
    tag: 1.13.5 # {"$imagepolicy": "flux-system:wanderbound:tag"}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wanderbound
  namespace: wanderbound
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: wanderbound-chart
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 1
  values:
    config:
      ENVIRONMENT: production
      PUBLIC_URL: https://wanderbound.raveh.dev
      GOOGLE_CLIENT_ID: 630509937439-d8gtaum419mq8elhvu46244krh8or9pp.apps.googleusercontent.com
      MICROSOFT_CLIENT_ID: 6234cd5d-4f13-4a21-bd0e-8485e10193fc
      MAPBOX_TOKEN: pk.eyJ1IjoiaXRheXIiLCJhIjoiY21uejIycDViMDZhbTJzc2dya3hkemlidyJ9.gZAiZcb5u-KJ0NEo78z8sg # gitleaks:allow
      CONTACT_EMAIL: wanderbound@raveh.dev
      GITHUB_URL: https://github.com/itay-raveh/wanderbound/issues
      AUTHOR_NAME: Itay Raveh
      AUTHOR_URL: https://itay.raveh.dev
      PUBLIC_SENTRY_DSN: https://1d5a9cc11a320cd76640350975837459@o4511082013589504.ingest.de.sentry.io/4511082170941520
      SENTRY_ORG: ravehdev
      SENTRY_PROJECT: wanderbound-fe
      UPLOAD_S3_BUCKET: wanderbound-uploads-raveh-dev
      UPLOAD_S3_REGION: fsn1
      UPLOAD_S3_INTERNAL_ENDPOINT_URL: https://fsn1.your-objectstorage.com
      UPLOAD_S3_PUBLIC_ENDPOINT_URL: https://fsn1.your-objectstorage.com
      UPLOAD_S3_ADDRESSING_STYLE: virtual
    existingSecrets:
      - wanderbound-secrets
      - wanderbound-upload-s3-creds
    secretEnv:
      SQLALCHEMY_DATABASE_URI:
        secretName: wanderbound-db-app
        key: uri
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 5Gi
        cpu: "2"
    persistence:
      size: 50Gi
      storageClass: hcloud-volumes
      retain: true
    ingress:
      enabled: false
    sourceMaps:
      enabled: true
      existingSecret: wanderbound-sourcemaps-secrets
