apiVersion: v1
data:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:ASOMkPyM05XFgB7pZOkJitgv8OGe+AyQv5ZtkA==,iv:qIdUX1mC1xNWjdPSjvCRf0h9ftN/SqtZNOU7cAbBkM8=,tag:bThpxh4knoagD4dm5Czm8w==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:AB/2SmmuM8UzHRo+pJcejk0Nryz+uhVLxI0B8A9YJAR811jFk/VG6/lDoJAruTLLto9rVfrtGyU=,iv:bxAf9T9+yvFYHT+oDmOPuk4YxXwGp9ADVPv9EM1/9TA=,tag:K8wppcwRzN+67gs7retsNw==,type:str]
kind: Secret
metadata:
    name: cnpg-s3-creds
    namespace: wanderbound
sops:
    age:
        - recipient: age1yubikey1qghympnz70sye3tx2a9yvudmmnvrq3ms7yd3gns8wz76r7k46hx0upwcu33
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDJDM2Y5ZyBBODBtQTRi
            Zzh6OWQveVRmcGdPSEtEYnZwYXY3ZmZJdm1naDliY3hFb0J1YwphaXZ5RXg3dVcz
            bFlCRUdBVTgvNVFIRktUMW9IMlhQbHV6UWhlN1lpeGxvCi0tLSBTV0loV040TlFV
            ZkRiYnlzcG12UlZqaFhoR3JjM01WL1kyejRoNzlub2t3ChzkLbpLF25RaAiaN6g7
            Tcf3TLYGgTC5qCdSHqW28pDStNel3+PQKpHKz+yOmLbzZFFyPtkruyJhidOl6XCR
            UKo=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qvcujpaxamuraf4neev9xcxgj40e5x54n5a8kz0xvg3fpcnl6p48xsgkyg4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDUyTHkxZyBBaSs4WkNX
            NmsyWFR0aDZzL3EwYlFna012azlHanNHODZ1Uy9MU044VGh1dApYRG0vRXFiLzlE
            bFoyR0svZVFqYWpYcUg3UjVNanpvaHdOZGVYYnZWakNNCi0tLSAxSjlIdzB2UXFj
            d1VvNGdHNkhhNXNZL09IaUFtK1hIZ2syQ0JKaENVZEtjClwV851i/iHuII4DUDR1
            DfrLsPullK8jWkacqJtczDG02PNVMqqd1o9r5s18EHpuIoLIoGvnrLiWdXnRkxX3
            PQY=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dhztnm2nhdpcwsuv8uz6ss05tdx4jyfhm22dltu9l4u4fu8v3a4qs5asa7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbEdWZkhsS1hFZ2lCM0NS
            bTdhRUxRUEFDZXN0RmNJaGFpdTR2WkYzcUJJCmVyRGJjUGR4bE82dWRob1pWMS9n
            TWRTVkZIdHFEeklJL3UwUFJVRzhjMVUKLS0tIDJLZ01IaVdNQmpIdmtZTkc2aG9v
            eUx5SzJucHdDbE1zZjlVT3ZrUnZVVG8KpzA6/14mtfM+TOttEcKkP1mm1F0gpKjO
            GQzHlvXU7OOPHB+IPEkt87VHJctxnnGs3utLMyGfrBTY0wfK51tjsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T20:34:23Z"
    mac: ENC[AES256_GCM,data:7m0tihfFzauqzOZMTATanu7eVsetdlTX69bmB58a8zG9jReSwIsYR9uTYE0aJYb8P3DENDrK0RhWrhaicGogyCHB8ZnlbIgtuHiz13DGb+7l80e/MjycFewBdq5+GuxErCvp/xNzuwhZMCrnhpyZ5vfqHc/fC9WvozVtmKrPTnE=,iv:bRbbpp6TZ9/kXvm2JbWH1DbUJgShTDRXxLi1xrdljPo=,tag:7Xhgf6A62qLzfvkkV+XhvA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
