apiVersion: v1
kind: Secret
metadata:
    name: wanderbound-backup-secrets
    namespace: wanderbound
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:K3aUOdNtFt8NXHVDZV8GlBpYhB+eJ5fV9Hl/lEAS4BZItXFHaKcAjCX3O85rbbXRdVklpy+V7c94qijn,iv:8KM4Jxc2+9eNtLu6IhAME1ASKpXU7WEWX04T5FA6BEI=,tag:Fwpe8o2anAl7AYeXqqWEFw==,type:str]
sops:
    age:
        - recipient: age1yubikey1qvpg35e0zwywyj7w6dv53yewum6mpr0mzkekpcr02mvzrrtml3zmumwhqae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IGdDSWltdyBBbHNDSkk0
            YkJkQm8yWk9HSHV2cXJ4VUtDeFBPUlhGRDF2Zm5ncU5kWGV0SQp6WkMxMXdMY0Rl
            MGM2b1EvVjBCNXV6WUJYZVdPM0x2bWhRV0lVSW5pak9vCi0tLSBxcTlWVmlDVVZm
            bG55K0hab1E2M2FBaldSZExiY3lmMU1zMDR6UHp0cVE4CkDYh6qhnJmAIj2zM2pV
            0GZwn6PMvDdXzD0azxqcqg48QzUNAgCCiwUgqcN++JZPCXntROZOff3+9uIOEZVI
            shA=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qvcujpaxamuraf4neev9xcxgj40e5x54n5a8kz0xvg3fpcnl6p48xsgkyg4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDUyTHkxZyBBMVR5aWxU
            UUxXV3Y4cXRjRGFZcForNFpxQkNaMzRZaWxhbjdqekMzZ0ZSRgp1OUFzRDlTYWtS
            dFdzTVVGR1pVYjluZ1FsZUFBaWp5a29mMTRRRWQ2cUZzCi0tLSBjbE0xVUZuY09G
            M3RIQWV1dndOdnk0UDZ5VmtPeThmbUF6R2JpZDNWaWxZCuLD1d1R36Wd8FATnzq9
            ixdMDx6pjbDloWcDxjLlPCCt9TWPI0F0RXSIvu8oY3DgcV0OQ5QqeEkSzsEYxY1U
            jNo=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dhztnm2nhdpcwsuv8uz6ss05tdx4jyfhm22dltu9l4u4fu8v3a4qs5asa7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHT2FUb2x0dHZCQ0w0Z1Vx
            VDVKNGVKcWZFN1NMNnZ6ZjlENUdBUGthMjA0CnROZFhWRVRvSmp5cVpuUTBiZUN1
            N2dkeHJYMXhvK2VzTXUyRjBKWFZVbWcKLS0tIGJpZmovcG5DNVAycGF1bDlpMVJn
            Qk1yS1JpWmNXamNoR3FTOFRkekdiczQKFXMmetJ1MmLw/nuqstBVLuki7fdoT2q/
            +9+36CMRncshVUO4sycXXJi0T55Eri1HCkckjKrdWtjSKwgmsfHyAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T17:06:50Z"
    mac: ENC[AES256_GCM,data:b4sdi7NCJYOlgsZKPb7lhhLWYGndGctDL4ZqPrgtAU1q69PeNFbWe0omzjXHHV4Pvu3i0s4MaskQRbm5u7Nmb1W/jGTkQ/L4+nt+j42NnEOYMDGS7HaFX/K972uvI+SfF4K2VG+Z5hNy0YyLSRUsMzTE/gbMVnDTBDjgjtBRaDw=,iv:oflIE0Pid0H7c8gyWHpqajeusZ1o3MPpPLEw1HMdEKM=,tag:EK1QkXte0M40qav9UeRvSg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
