apiVersion: v1
kind: Secret
metadata:
    name: wanderbound-upload-s3-creds
    namespace: wanderbound
stringData:
    UPLOAD_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:zzZ4bSc+ugP14eYpfkyJtO7vye4=,iv:nKpnCHcLprkD3dOkGyl+jNqiRcblzPFGC2dUpeqM0sM=,tag:hdhjPCKQ8LVH76JxTcxulA==,type:str]
    UPLOAD_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:0P/xkUNKfYs5UWgMHFsIqVNeT+p6Hxdg/a1FejF7VZvNzCDp1BoEyQ==,iv:0WvVAuDFy8xCtCInjGcUDYcSXGgfgy+99pzw0uToc5I=,tag:YqP67jHF9AKs20NVFqNgSw==,type:str]
sops:
    age:
        - recipient: age1yubikey1qghympnz70sye3tx2a9yvudmmnvrq3ms7yd3gns8wz76r7k46hx0upwcu33
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDJDM2Y5ZyBBOE9RemJ5
            N2RyU2NJR1N2ejR1aUxRUmVKaE8vQUF0MEE3MjIwTDBpeElxMQpOYkwzYU5TcXBH
            SCtqMXQrSkVuN29TejBVYzZNanpaUlhGQXBEMTQzZkc4Ci0tLSB4OGlNZ0ZUbGhy
            dE9mVmhacHpzYzF2bm0za1pIblpDY2U0WEZuV1JuVEs4CnsgCLaNJ6RJEJwqhjl6
            CzUmqpjhx3AnyJSw8xQUYVkz+c5JNJS0hzPokh3rjXDbCFbL0wOt7eORDIYNDX59
            tQA=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qvcujpaxamuraf4neev9xcxgj40e5x54n5a8kz0xvg3fpcnl6p48xsgkyg4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDUyTHkxZyBBLzI4Zk5s
            dUFjcXM3MzFQK3JYSXBZcnFaY0RKUDUzUVh5a3FQaTRlTVI0aQp5Wm5SQUxpT1BK
            d3NIY2lMVm5rL1I4ZEVYZ3BOTWdndU53eHZ3VUEyQ3lZCi0tLSA3RVg3R0YzUkh1
            TzIzQnNDWi9Cc2JmcmhscHVMOXJvZ3pxZjFScGpVeS9jCpaq0/rmCcawxM8C64P4
            XxF9YCfQ0M0WgW425fxhF/hA4zFoB1JF1utWSasj5phIGuFgS+8ugzfWTP1TWjzh
            Cjk=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dhztnm2nhdpcwsuv8uz6ss05tdx4jyfhm22dltu9l4u4fu8v3a4qs5asa7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNEhlaWxNam1XSCtDY3BP
            L2c2ZUppcGNPZEF3eTFXM0Nzd1JLUXMwejJvClpiUWxaQTcwK1lPQlRzTlNNZFh6
            V2ZwUWxDZUJVZUhZbm1MY0xqd2w0am8KLS0tIEtadnVPb2k5Um5Rc3hNNDM4a015
            NkZ2cWk2cW1pNlVJYXhHbHpXcnpyVWsKk41EgH3qKFgkUbiX683TZ86EAbySbQpq
            CRs7chnwO+pxkD887p4WspujVNCaxlGnjzcJ5gyWgaQ6SwE123u4lA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-22T12:45:18Z"
    mac: ENC[AES256_GCM,data:eY+V8QR9ttFBN7OaKc5DrbpQefxjyON5mIEdk9yA+9s7N47i9koWHxmLWr06xZEDu33qMuftiJTCIhMTMfVK/mZA9MQeTwfTX0/h+26BuHe/1U2WJ9xQ4gkE7FFN+H1t/rAi32gtZGfRT8U8Ple7zztnldKnaBJ1IhG2PMWDS0U=,iv:v0CSsyKVE8zgUiYnLN9dznsQqdfpGYE1FJUF1i/D4hs=,tag:z4rOHOkd+PEapxzmG7aJzg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
