apiVersion: v1
data:
    SECRET_KEY: ENC[AES256_GCM,data:oEWVFWLwoV2o5xyAmtGDul46e3sy2LT6nOWgIVl07rLHj1n83EhBxIao7xJZKWYRK7JAA0xap8T0INnaW7PWEFmc9TaNmREDV0ePsMZnFYWvjHF4K3iWww==,iv:efkEzkWQQxNu5DF9tfC/GYpuuChludbmmSAJAhr7fQE=,tag:I1KTAtYPkP9KpY01iYb2QA==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:XDC6kFWcCQSLgPqie2Y+wC9ueODnyhV40MxXYt+wScnIC2r/8mF0tIEyl2kPDAeW,iv:KpGdEmCjoUFqjglHsGbFdPLXo5/AmuS8gZPBpDdTA7Y=,tag:vTl3X8WiUg3WU9kaH+7sMA==,type:str]
    SENTRY_DSN: ENC[AES256_GCM,data:MOd5TcWWRhzqkKiKyyoTAfKi5zeTC5bR7AJFYCSxLqmNH9vYqURkENnmISROVgNUFBN/DssB9wylzgt4H+gEzORnFFTA7NN0TSR6KsCY19ocMmpQx63XNmKBxADLRz4UgyQnFgsTDkNvFUKDd97LvfNzC3otDomMSiNyfUyfr9c=,iv:4S/rGP6dJJ99BghVygomM2WmWYwKR8Hu4XTIhQhkakg=,tag:CR6Y4NDhBumemn1h21cBHw==,type:str]
kind: Secret
metadata:
    name: wanderbound-secrets
    namespace: wanderbound
sops:
    age:
        - recipient: age1yubikey1qghympnz70sye3tx2a9yvudmmnvrq3ms7yd3gns8wz76r7k46hx0upwcu33
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDJDM2Y5ZyBBM2QvczBq
            TzhNUklZazVubXBUcWtHak81dHJKUjB6Z0R6SWErMkhJZU1hSwozWmhzNmlIcGJM
            TlJCaDNGV0hDRTFSWGZKUjdWSTRjaHYweVJ5d0dLTU5nCi0tLSBiL290cnNVamJu
            ajErYllWQzF6NXIvc1d0K082K3dFR2h2SjltNHJVdzJZClr4vppptNeHF5dPErH+
            x2Py0Mu5qoU2jO73kE0TqXVZhcw6mPCIyXZA3+2C1IanP2a4rImuUFMKAd3xS8LL
            dc8=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qvcujpaxamuraf4neev9xcxgj40e5x54n5a8kz0xvg3fpcnl6p48xsgkyg4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDUyTHkxZyBBODVBMTk5
            Nk5NSnp6V0pOYVo3QTB1TzA1SEJkc0dGbzNENWVVU09qRTFCYgpzN3VablJoTnZS
            U2xISGhSc1MwRkJIa0RlRGhxZ0FtMzJxVWNNK2VSdURjCi0tLSBucFVNMmlCcmw1
            QUZDVklMaGJYcHV4QVVua2tLNkRtbGErWXJ0cXR1OW13CrHrJXjZf3+kYDd+/cX+
            06Aqz9D2QvLTkonnq/6QIPU1BaLVfcDja5Xr8aDViLuV0KV5hEsEeTAj+Xwe5mHj
            Jmo=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dhztnm2nhdpcwsuv8uz6ss05tdx4jyfhm22dltu9l4u4fu8v3a4qs5asa7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxanpPRTVkeTZsdTRtMC9C
            SjNnZGZubHJjNXpRV3ZmbkRXYWhyeFNyTXl3CkM0b2gzTHlHY0pEZDZwOGRBU1o4
            YzB3bDRVbjAvYlVQbmxHWTArVU5wZ0kKLS0tIFFINzJDTjlTZWc5c3REUHc4WS9I
            MUVWNU9kQXJ3TEhjK3BRdDZ0MGl0NEUKamBkyodfL0kCWJTIR2QwlqMPYcKRDezt
            vLZ7TNtv5JH2UNiIhjyE2dGTuZjHWXjGiNEDwqCLuaG4+k5hUxIzzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-21T13:35:03Z"
    mac: ENC[AES256_GCM,data:3jugeLu1RP0cO9X1umu5TlaLT2eBmLnFkroBJn49WJLesub4iUiPFYAtm7r171l0iX69fnBcxOgMajRMYtmLTcQsgiCBkd521QRaHnxSvxq92gdmZFsLmJO9qIEwJpiMIA9L8QPVZBFR+pGYvf/SO9RE9Hza31/I4BKoag/I8zA=,iv:MKqdr+mSfsl5dL+vg0Rtn35VDcC8sXgnSNnkrx0mIpg=,tag:Gjtl0v/Sk7JYYx4BGPCvNg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
