apiVersion: v1
kind: Secret
metadata:
    name: wanderbound-backup-secrets
    namespace: wanderbound
data:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:FImsS1pAsqgiHH5cTmQ0OHLu9VpcNy/7U3Ux0qHoLmG57yM4+wR/XIWArKID9egFmN6xwBlU3byghyby,iv:EHawMjAEfzUU6SK0BJrQNTnYwmqQwU+7u4hhlJyQgyE=,tag:rl2246HQRb/J2jST93uKrw==,type:str]
sops:
    age:
        - recipient: age1yubikey1qghympnz70sye3tx2a9yvudmmnvrq3ms7yd3gns8wz76r7k46hx0upwcu33
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDJDM2Y5ZyBBZ2VnbGhD
            cEVUc3RCSVhxVXp3NEd0a0I3WEZraUE1SnVaOW1qRHF6RVNtSwpqeFhaSGlCMUpN
            alpNRzBjbEVvZWU4NFQ3b2JNVFo2djYzbXNtaWlTcnpnCi0tLSAxbFBraEpwRkZm
            TVVuS284UEttV0lVQW9abEZBSnppRlhudXhrNUpkZUZVCpXUQmAF4IzUBIE1QdOp
            Vgne3m3sKuQzRmNdY4Dr/c2sA7dqfimys8GqSQWrtWgJKRL9Aa61BfljKeSCwTj6
            1GE=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qvcujpaxamuraf4neev9xcxgj40e5x54n5a8kz0xvg3fpcnl6p48xsgkyg4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDUyTHkxZyBBbzZoMU1Z
            cmlHcHE2TXVsR0dLQ1h1Zi9KUVZwcEVxYUg4VWZKcm9pUlphbgpKNmtsQ3o0TzdN
            cFUyRWY4Q1pMaTVPZEp0dnpCQWt1Z09aQUhZbFI5VW44Ci0tLSBuTmlBS1JGQkJR
            blg1R2xiU2NHeFpxTHVnTkN3SVVpWWtDeVgyNVNOSmdNCnCu85JuZsiykMuhM86a
            /ISgpnGtWwBJ7g2qdycHzZ3OGrIQLYc/udKwTAM4OumlAiNdf6Yt4zfaAc4pBKw1
            ynI=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dhztnm2nhdpcwsuv8uz6ss05tdx4jyfhm22dltu9l4u4fu8v3a4qs5asa7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNjlqSXZsNXZ2bms5WHJX
            V0ZFc3hOSHhCbzBlZGJOei9GZ3BXTDMrWTEwClJDZmR3TVc3cnN2VnRrWGorV3Vj
            cjRiVjFUczBUOVcrQWdad2htZWdsdncKLS0tIGdvTmZSOXRwVWxhdjY2VkE0YkVP
            QiszWVluMHZHcGRuMWs5TU42R0ZraGsKIKnpnKfzQg/oGFuB2SbWD0wfLVGoYWQx
            FsPmjc5x7quQmQNP22UwjwiI1jfMYY1gGV9+X/OUFgGR2Y0KsHerGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-13T16:57:57Z"
    mac: ENC[AES256_GCM,data:gUIRbsYVlr7m4FCHrW/EE4WOroympMJfhLfZlVxxsX9hqmZc3Xn0ExEj5GnSb2f35qmEYvsyHcE7Ys1MkDsQKEnTIsrY6witxYkz40ys13WFG4sO4uL5Fyux5wJxuajU94IzaLYyRIVHzO6lRdilkJ5NIFDDyf/wlxlkb6jsN68=,iv:guYSLHyVKfIS13d+tr43QPyQZE2jHyx1PevxcpN+M/Q=,tag:CMD1jATU4wC0DozpBu6uoA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
