---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: wanderbound-db-daily
  namespace: wanderbound
spec:
  schedule: "0 0 3 * * *"
  backupOwnerReference: self
  cluster:
    name: wanderbound-db
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
