apiVersion: v1
data:
    SECRET_KEY: ENC[AES256_GCM,data:oEWVFWLwoV2o5xyAmtGDul46e3sy2LT6nOWgIVl07rLHj1n83EhBxIao7xJZKWYRK7JAA0xap8T0INnaW7PWEFmc9TaNmREDV0ePsMZnFYWvjHF4K3iWww==,iv:efkEzkWQQxNu5DF9tfC/GYpuuChludbmmSAJAhr7fQE=,tag:I1KTAtYPkP9KpY01iYb2QA==,type:str]
    SENTRY_DSN: ENC[AES256_GCM,data:MOd5TcWWRhzqkKiKyyoTAfKi5zeTC5bR7AJFYCSxLqmNH9vYqURkENnmISROVgNUFBN/DssB9wylzgt4H+gEzORnFFTA7NN0TSR6KsCY19ocMmpQx63XNmKBxADLRz4UgyQnFgsTDkNvFUKDd97LvfNzC3otDomMSiNyfUyfr9c=,iv:4S/rGP6dJJ99BghVygomM2WmWYwKR8Hu4XTIhQhkakg=,tag:CR6Y4NDhBumemn1h21cBHw==,type:str]
    VITE_GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:YpyugIG/de/+zbK0efCoJFjol6ZgQrywPFz/HUpPq8Z3363453v4Q0xFHkzXJ2kf6pDehEmJQVhiUU1QJHPmYiIK9PEkhZUPsudrH9C10lBYAyrSdEtSbXJmw2aa80CF,iv:7hheqjrMAL2HAF/f/px/8nqE5sbD0OSrJf8PesoDbGk=,tag:egyPTs/KmtALw4CaozxJyw==,type:str]
    VITE_MAPBOX_TOKEN: ENC[AES256_GCM,data:zf3NYOjiIcV41sjieZLX5FsfRD8QBt2r0yiZxQhbZuGkOJkgZjyjjRuCAwvSOBorlsciAiogJ7BkKOe3j6U4jvsCl+nA+nSq5x9J0OY3bjyaYs1OaeLOSNoIuTx9nL4wZQ6hIwpcvRrjwAtkA1AjOK4Zcu0=,iv:s8owrSnWGjgv0+M+mY9W6yT6pF1JjTrAFA++o5dg0DU=,tag:XrE6P/BZthPik9+0xq+y6Q==,type:str]
    VITE_MICROSOFT_CLIENT_ID: ENC[AES256_GCM,data:OuG4XoJF8O4KtSX9GN+o115QrKeqA2HvJtmkkhh6J0SLwKIpN2HHPIRRlTp90gcA,iv:XMbHM7mCV52N4OrtyTkWeJchbh1tn12JKDjEVwlAP2o=,tag:syaGwECpzljiXyYYUlT/BA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:k13YZEutTx/UzzZShFeM/NuFHDMBGCvJjGiydsJTr0wsRJP14xFhi7A47FUscbFnZj1WahIAk1nJgiFV,iv:EDabjR8TngK4twJ17yAoR9GqZDLW7NtfzaUMcBGScYI=,tag:pJeYWbwN4TveNjAlA2IgIw==,type:str]
kind: Secret
metadata:
    name: wanderbound-secrets
    namespace: wanderbound
sops:
    age:
        - recipient: age1yubikey1qvpg35e0zwywyj7w6dv53yewum6mpr0mzkekpcr02mvzrrtml3zmumwhqae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IGdDSWltdyBBeHpNZjZa
            cTg3M3ZMRkFTbHB1TTliZlArMDJDekl1alpMckZuYVBVa1ZxWgpzQ1R2aEt0V1Jl
            UU5TbjZ0ZVJsRURKUmpYK29QdnRnKzBDQjYvMzBDRFVrCi0tLSBmM1g5UGJmWTZR
            N2JYSmh3d3hjOGp1MVNGOEZUaGFKRU1QUC9abDlKSm5ZCl95W2qH5Uq+DS1NwXDs
            JjaVPuH66QP/KFYOTTEezBcX9xmh8TtTnu2DP7MU4x9xM3HzBOxKPFHk0Uol/qFq
            K0k=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qvcujpaxamuraf4neev9xcxgj40e5x54n5a8kz0xvg3fpcnl6p48xsgkyg4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDUyTHkxZyBBeGp6eHZq
            S3ZzYzdNb00yWStkTEdlMCsvaEFmWDNIcnNzTlhoc0lZS0ZjKwo1YStCNHZTTmtD
            SjFlR2xIQnRoczk4T2VXQk05UDlzYTJpNGJUdU9INklNCi0tLSA2UllXQU1PTWYz
            Z3ljcGVIQTMvQXFCWFZrR1dDZE1hNkhlSWp3U0VkbDdjCoyZ08GtdlwRKK38myZR
            5FhebD+JyIO0xfepaWNRAPlQZDpEvlq0TnOLmY+fd2cXotFjfDGSeM2wmrPqcMDx
            GxM=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dhztnm2nhdpcwsuv8uz6ss05tdx4jyfhm22dltu9l4u4fu8v3a4qs5asa7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cVNqL3A0TDZ5TlJ4Z2pB
            MnRiZVR4amFhaTdrdWZPM0ZjT2dwODl2WEZzCnJQOGtkQ2JkaDd2d2p6Uit0YVhk
            QW1OKzAzNGJJNlZVS1lmYmh5MEppTjAKLS0tIEtVZFF6b2VpK1dWTVJxdkpJbG8v
            RGJnREZ2cklqbnVJVzhSQi9iM3NQd1UKsFuSddqe3HXdDYN6YhhNziPO5/dsQq7K
            yiIuQSErnlmdIzvAv1JVLgMIKBrFb5TF4ydGTYjoHZQ1PAJBjPCPBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-14T16:56:31Z"
    mac: ENC[AES256_GCM,data:SF7rALKeQ4KxsNSvwoT5QwVDDuSsOzRjh2tTLiw56HHOYGH6MwIYrTNgW8+tseLsFaCyOKyCWQ5PmGgdH4f+UuUmEwOHMP1m1+y5tzKOY5lyfls9gGLYijkjecLXbBlrxN1xhaTZUC7sxjXuz2adiYxCNJDeMUCNErPdbVaHyrA=,iv:P2qDKAqrdjDxJDtVeMZJgzDMfMI+LnIO1LNhi36iVwQ=,tag:Qp0bNP2pEGfv/znv8p8v8A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
