---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: wanderbound-db
  namespace: wanderbound
spec:
  instances: 1

  bootstrap:
    initdb:
      database: wanderbound
      owner: app

  storage:
    size: 5Gi

  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "1"

  postgresql:
    parameters:
      shared_buffers: "128MB"
      work_mem: "8MB"

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: wanderbound-backup
