apiVersion: v1
data:
    SENTRY_AUTH_TOKEN: ENC[AES256_GCM,data:x2NwlzKqurX/8RYAdJFdDVQ1JgluNEOv8WBPGwDFAf72zoObwPgEc8Ups8KYU9VzkkudoooJS6SkrvlygsVXxjqVFsmmIYaI1IDOKkKTxL4dddVj58rux3q2/jo1v5vBqveJktUo07+CRNXeHir3yg+saV+llYLqStWHCnCP1hLEika5RhRQ2NH8ZTencVTclXvwCzkf4IalAPoFI4ULPGZel2RxPf7oaZ7cN3vkZNTyjn858aKYmnAcrtGR35koHN5hPPskPEsN+Iim9RXyhVgQ5qkcKagXh44x24YAZdLPeG/irmsgINASTpM0ZPbaMZuKk4ntlMLoje8iPmx5bg==,iv:Zhre+STzjp8tkuFxicfOhGKpvMY4+72PSTIz276w6kk=,tag:BAf0eXKJiAZdMUzporyP/g==,type:str]
kind: Secret
metadata:
    name: wanderbound-sourcemaps-secrets
    namespace: wanderbound
sops:
    age:
        - recipient: age1yubikey1qghympnz70sye3tx2a9yvudmmnvrq3ms7yd3gns8wz76r7k46hx0upwcu33
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDJDM2Y5ZyBBamZxaXpX
            bjZ5SXhFWDd6Q3NsSjc0dldERkphbzdELy9MMUJwT3hWV1k2awpCSWN0ekFKYmY1
            Y0QvVDM1REVmR0NvbDVBZlorMjBySmxyOEhWbUlzT2VVCi0tLSBqcnhiSW9nWVN1
            bzQ3c25qM0dRbWJ6bjBVOHVZZzJmbDlId05KK21aQWh3CjJLkIulWEDsrfss7UvR
            8PwHcyCewhtJjUJn97IqqDmiWIUifQIzbErcnzB5259pAOgxXjNJFJkuSaZOjyIZ
            xhI=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qvcujpaxamuraf4neev9xcxgj40e5x54n5a8kz0xvg3fpcnl6p48xsgkyg4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDUyTHkxZyBBNFJMRTUx
            QkN2RjhJN2J6MDlzWVh3NTBMMlpzN054cUk2UjBZZE1aQ3UwRwplOHZ3Qmt4U25z
            QTJ4VGVMT3N6c2FPMzBSWmxyMmRZNVBWTk8wdmxISDJVCi0tLSBLYjVLOUV3ZDgx
            QzhMUkJvZHlwMjdLQi9idWhBM2ZCcXIwWnVKY01BcG1RCg3kSSCMxIVigjhjTyu+
            pVyta4k+rTKjp6Mh8f7OHdbAO1pf4hHXNfHFGxTdO/i3Av0/7NdrS57Mmob6KIF4
            S9o=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dhztnm2nhdpcwsuv8uz6ss05tdx4jyfhm22dltu9l4u4fu8v3a4qs5asa7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZEtNZ21GTnpKYnR6TEdu
            Vmc3QktKcThPRmRLTDdEbEFPWGtqMmNWSkFFCk1IVll1RkNqUnFNaDNhakdodE5q
            azFQTDRMTGY2a2xvcnFXRElkTndMWlkKLS0tIDk3TWlOZGowYjlTdXVKZHdjRk4x
            NDlLazIreEtOQk5HUWh1ODdrQUNEL2MKk4rLa1qvlZd9sH+cUoRR5QnGqKQuoCJ5
            bVhNUl/GEuZht4q1CyB84aqAN3zzZglfgs5s5B7AL5+5GK+sbJjBBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-21T13:36:30Z"
    mac: ENC[AES256_GCM,data:A/PJK14kddzyXqQwQrjUdNaZ6eu9/miPxwmD6Ub1Em6ZE2/nxJ2k9rA+La/OssYinvDP9c43e+rEdSuk0+i4cio4pGR1VIqPwHfdMI1MLFWbijPTryN1zwxPpG8IVBLKkjCHQazA4wDo5fQLPDYgLfVaOPUR8XYg9Y0QleK2maQ=,iv:pAYlVaIgZRw3XIHMYYbImup5CZuzbWgH3BJP6kUnKec=,tag:0d927WYlhBpCwEVBRq+gPw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
