---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflared
  labels:
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudflared
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.kubito.dev
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: flux-system
spec:
  interval: 1h
  targetNamespace: cloudflared
  chart:
    spec:
      chart: cloudflared
      version: 1.7.9
      sourceRef:
        kind: HelmRepository
        name: cloudflared
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
            patch: |
              - op: add
                path: /spec/template/spec/securityContext
                value:
                  runAsNonRoot: true
                  runAsUser: 65532
                  runAsGroup: 65532
                  seccompProfile:
                    type: RuntimeDefault
              - op: add
                path: /spec/template/spec/containers/0/securityContext
                value:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                      - ALL
                  readOnlyRootFilesystem: true
  values:
    managed:
      existingSecret: cloudflared-tunnel-token
