apiVersion: v1
data:
    cf-tunnel-token: ENC[AES256_GCM,data:qSAna8nVhYT13Zs+8Q0WrDyMfhPValG2N8xygRGspPVcXsxLR6F5d3IjwFOMQ0ewg9Rx0y6+I5v6rTHQJmb6jPYjmwuuRilyTHrGy3og8duKGueaNqRnagw+yfua3QPlGAt31s3/269NclIgJrzEos1g2AtHeRaodZHTUMUgqRPXFDq7D7U0bZqY3Tzyog+rqICAqPfv1S+m3WzrFNxHVsTxhr9MCGCZO25tex/2mLfqOqhaa2pu9Ey3NPqsYKqUGTwP6MrTLqxgwaH2TIA9rJIZLRo0vcR8ywpB75hu+6404tuRuGNWDuE6ILTOlMUu,iv:DNj0JSajAKy8Jq3jJKPDvTSz391dbewjGb5YSKwhZjY=,tag:maquH8Wk8V/fpHOY/bOybw==,type:str]
kind: Secret
metadata:
    name: cloudflared-tunnel-token
    namespace: cloudflared
sops:
    age:
        - recipient: age1yubikey1qvpg35e0zwywyj7w6dv53yewum6mpr0mzkekpcr02mvzrrtml3zmumwhqae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IGdDSWltdyBBOXVOWUYw
            elF1eWdUcFhNV1IyVlo0dzVUSVJyaXFuOXhGdjJaNFRaYmVsNgpabUsxMHBsZjhr
            Yk16akJoRXZmV0U0K0U4QnpoTVdxa2RWVXpybi85bDc0Ci0tLSB5MzVHNE1rNEZK
            Z0IwRVZlRUlFMW15TzFCU2UwcTlEZkhzdmEvdk8vRFBBCkZmvGNkw19N850Z6q5V
            aNJopXWsTeKh+m9G5B8kYx92N1nLIQbqrXFuwiCIRmNC/bdZZuQPlTS6AJwnS6kt
            FI0=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qvcujpaxamuraf4neev9xcxgj40e5x54n5a8kz0xvg3fpcnl6p48xsgkyg4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDUyTHkxZyBBazNJaTlw
            MFZPbWx4b0czMVI5MEI3cUI2bExmQnlUVlQxZ2pacHBJQkkxVApKRlBzSnlyUXd6
            ayszSFBKK1RLUFNSajZEckdYWDQ2cnExTWJYT3RqMkw0Ci0tLSBMUmxYQ0NwbHZM
            ek9zYjhhRXBQMTFSYVhycCsrTnhqeU5pYXoweCtwOUJNClCiNwTughh7OUuxocsY
            clITetPjFz0FV6ZZ7RKtt5z7jaIJqieE6JSwrorySB+TaA0mdfEDqxlnPTv6Ifyh
            8qs=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dhztnm2nhdpcwsuv8uz6ss05tdx4jyfhm22dltu9l4u4fu8v3a4qs5asa7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNGNKNkVlOFNhcWp5L2RL
            dEMvSGpkMFdESzlsSm9BNVBrV29OQkFxaWo4CnFVb0dsc01ma1BNeGF1VVN3OVVH
            N3QybytzMzVVVzRNeCtSWGNoZG5CNDQKLS0tIEVncTlWVUhybjJIVWJhbjlzbkNx
            RG5maHNOVkxuUkJMelNXWUwzNmRQODQKXhSkCWlatLOhX/MeyS7kCfj+MUhQKF2l
            9C9Vn362CM0G8rcoIM8IDGDcNvTeuz+N/LjMWO9/GS19bPIu7ZAprQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T16:51:55Z"
    mac: ENC[AES256_GCM,data:0CeZ0CoQR2XV3e0qfXlPYzqNNw48K/OZeKS0WJXKqxAFxaLWN1pnKvMDhf6uo/QEfAGK2H9CDSFRmlfzdfcdY/jmEqNPVgGzrFXngto3agdoWlb7yGaFazxx3IELQ9wO+s2HocTtM+P+slld4NVd1fQyj9C4yojsJ2Id1Rdgb7s=,iv:I+WLERVBHpi2uNEzdR8awZBgFdx+G+9sbwT0Gb1hgJ0=,tag:RpfzSas1pTDeqf3yWc8feg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
