apiVersion: v1
data:
    cf-tunnel-token: ENC[AES256_GCM,data:kCkJhl35HLB1tQkbvG6thyUmtAEVuoZKCFy4zhJL3ovDaWrDfUtX2mFVTJ2vK4P6BOc+ykU2tamkcqTD0Hwn9AkTV7q1BC8nTC9z8GMgJl3dd0sp0Z6bH6zH25967N5I5gccrAGB5Jceov6l4jUofeW8GT38PT2LKCmTHap8M65fS3eFSgicdggR1f86cx+MCNDSeWW8qefeAx3EvCTZh5rRsLbAevLFkAklviWi6CpPLKZbZSr0sOOvbYWWxTDJicB3FKRoRqTvbbDtzflF1w+EjnrjWAUDvw3EB8yyjTwCyfbIER9YTgH4HogHIXJl,iv:KLZPGB9ZnWy/2q6gLpGUVFOgI0y1qXKsf7846xYr/AE=,tag:yDbguysT5e52Jm2BZAunDA==,type:str]
kind: Secret
metadata:
    name: cloudflared-tunnel-token
    namespace: cloudflared
sops:
    age:
        - recipient: age1yubikey1qvpg35e0zwywyj7w6dv53yewum6mpr0mzkekpcr02mvzrrtml3zmumwhqae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IGdDSWltdyBBMVExV0RP
            aGtMY1h5bGJjUkcwOTJCWCtjUEZoS0xZbnpvYmN4ckI5WDRVaAoyeElvUkdRZUF2
            TjI1Q2JpckV4cmgvTUM5d1pxODZLOXJYTWpCakpsYnYwCi0tLSBxRy9UOElzTkJX
            U1N5L0JlVWN3czdtZlFTL1g4VTVMUVhxN09pdzgwRnBRCtGUdZqdiinFJkRz6/zk
            LyWjxmzSv+mQQJOXe7/xvQvTTKa64f0TSowr4rKa8Yce3Fo6tghYlyTeOxwBhumn
            sgA=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qvcujpaxamuraf4neev9xcxgj40e5x54n5a8kz0xvg3fpcnl6p48xsgkyg4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDUyTHkxZyBBaUtwbVVD
            VXprMWRWdXA1cVU5TU1RWDZRMG9FMnNyMDdRR3hGN3RGNTRwZQpxUDRxSTZjcWZW
            OVpISURFNW9EWHVEOEo3UEZiRE1NdUoxODNIZDVNZUVnCi0tLSBNVG45cDgzeHRm
            OEhBWXlYeWlzS056Vy9SNnMzUnQzaE9wazRKZERnU0FnCp/SXb9k1vNL0hIk5v3w
            sxyLejhSMfkBhwa2lp36XBuh8b2zzqEpNT/8gjfqxFhMmA/taPYB+PsaoNi8okxn
            StY=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dhztnm2nhdpcwsuv8uz6ss05tdx4jyfhm22dltu9l4u4fu8v3a4qs5asa7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMldOdHowRTIraU40cldP
            Sm5XRi9SME0vSngvMTdUeFNJUUswcUxnNkhVCkRsME4wazI4WW93VlJXd2lyM0Rt
            Ty92bnFxMWs3RUNqaVU3QklEZXlJL28KLS0tIEJZZzNwOFdyRkRWRlFmSFI3cW85
            aWVBL3lqY3Y0N0gwbjFwcnlCYWhmVmsKwYH/2bsev0uci/Xy5nte8JPjGeL7exuO
            5dqogvZSsv5CvHchCgeDZ5DXMPdmtWAjg/SWN1C9biRWKi0R5pCosg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T13:27:19Z"
    mac: ENC[AES256_GCM,data:fhkKF050WTu6pAcDVMRCD7xEdaoQE0sZm4NxP7xfAXE8HPDBm2CiCRq6ajBzJlU7Tu58f0rl99fy4U+unZQ+4rsN61OWJV+1Zi7lkIUiQ01sePQFOS1teFQrfDkGhZYqnbJt8gHO2lVfRLyz7xjSpWiLvodiNBPiuRBvlFq6cZ0=,iv:7lzUsTGOp9lkjx6NWWMGRzZ0t+cy4lfMNu5ZxOqZcgI=,tag:nyxnwIejyuMjaGMfv6XPuQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
