apiVersion: v1
data:
    token: ENC[AES256_GCM,data:sVQJBvuOcRpAjKqmtjF0rtDorAhW5grHSpK7BiX+aV4qYQ6VCejesKY3h+aeV/BrkIA+4QOs0FfYmGECkSLUyVpi3tGdMfxKEF5a8EmgdgS4Txhi6PTGew==,iv:enlVx8DBqH2k3nxzb4PJyK7JY7hqWeBCbe9i62ackSM=,tag:c2cfl+7Y65oHhlyWtgcj4Q==,type:str]
kind: Secret
metadata:
    name: hcloud
    namespace: kube-system
sops:
    age:
        - recipient: age1yubikey1qghympnz70sye3tx2a9yvudmmnvrq3ms7yd3gns8wz76r7k46hx0upwcu33
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDJDM2Y5ZyBBL3Qyd3pt
            b0hZWWRyZlZkN2w4T0dWTjU0TS9OUHRaaUYxYkN2NER6UjNUKwpSWHVJOEFMc05M
            NGhLNFVheHVtaVRBa3NkMmlNdXh1cUIvKzg5L21HOUJNCi0tLSBCeDBzMHo3cmxC
            SUV6aHNaZWwya3k0V1VWd1ZYcmhMQVF6RDFRcEFZZUFrCuiJEIkcUWI/wMpFXNxZ
            sfgkNXLVzO3K/NJRKk8l1/NsLHOUQR3FIAj86h9F2u35cTmBFbewxwrwynFJB9xB
            ZxQ=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qvcujpaxamuraf4neev9xcxgj40e5x54n5a8kz0xvg3fpcnl6p48xsgkyg4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDUyTHkxZyBBdnZ6OVU0
            KzJRc085RVFtTkI1cmw2T0VVM2phdXl5V1h5bFFxWERuMU1FYgp4dllGbHRwOFFO
            MzA1N1JWSVh3NWNBbTc4VmRFVG1wbnNXaXJncndDSFcwCi0tLSAwcndVNnVsNTZo
            L0NzeFU0aGhvSHNlZ1BzbnFVNEF0Ymd0WTRXazJOZHlRCgHrrrGor2QhSFzT3cj3
            40bL9UYWwih6TW8pmwRSUOuA2xqKpF8yhZJoUcSVexYlj4I0SXKzukAxVbWRNq0e
            HhM=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dhztnm2nhdpcwsuv8uz6ss05tdx4jyfhm22dltu9l4u4fu8v3a4qs5asa7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Q3dtemRleVNwMGxnd2gr
            cHhqbmtlWldXakI1YXRFcjFJSXp3a1BOOEdrCmhYcFhDeC9hMWlsYWdlb2hBUy94
            ZnVacEhPY2MwNHZoODBYWHMrT2F4V3cKLS0tIDdPT0RmNlNXUGJqVEZEUDE3Z3Bx
            V2JMVHJ0LzB6TUFZRnVzZUorYlAvQUUKeCVrusfJ0fp5LlO+0dIeVE2ICz6A/F4F
            KNMiQZZEBMKQNnxYjP09s15CguA4izcFAYw7kwplQlO+1pTs6BwdHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T16:28:46Z"
    mac: ENC[AES256_GCM,data:rao1z/woc6vE1pqSZJe5+VwxO6VxfQEERR7K78IM440+CfI3Hy2BPYm/ZtpHTYcvzrSeOZ5++JJJf5hzP699kZl+7KfAVFiL9MP4IZWBouyJi5/erheDk0vn7t+SDx3rJB0WvBo1RG0nu7uqpg8YcHbFAqaa8VREIzDVqc0hRME=,iv:V+Rq8yxO37IhYPY3qTPaQTxRQLNuGs20rZuH6P7XI+M=,tag:W6IKkgmETTo2e/kQvM8osw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
