apiVersion: v1
data:
    token: ENC[AES256_GCM,data:sVQJBvuOcRpAjKqmtjF0rtDorAhW5grHSpK7BiX+aV4qYQ6VCejesKY3h+aeV/BrkIA+4QOs0FfYmGECkSLUyVpi3tGdMfxKEF5a8EmgdgS4Txhi6PTGew==,iv:enlVx8DBqH2k3nxzb4PJyK7JY7hqWeBCbe9i62ackSM=,tag:c2cfl+7Y65oHhlyWtgcj4Q==,type:str]
kind: Secret
metadata:
    name: hcloud
    namespace: kube-system
sops:
    age:
        - recipient: age1yubikey1qvpg35e0zwywyj7w6dv53yewum6mpr0mzkekpcr02mvzrrtml3zmumwhqae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IGdDSWltdyBBemM5WXdr
            bnNhK2E3V3NVYS9sMnBJcERnendaVWNKdUFnbWJUaVRGdVBvQgpaSVNraGMxNUo3
            YXZkWE05dzF1OXlFWmc1SDRpNURsTzNiYXl1UW5nWXJjCi0tLSBJVmNQT21ydXo1
            RFUyenI3OVhxZkVUMzIvSEdVcVFYRzhINmlsUjY2R1k4Cmt1KMP1NV4O1lrRs6Cx
            qpkU3ZrCnt4/2B+wLyiX5/wsFvVl9F7SVEmFK392vnuabtCD1wT2SHx5FijPeBxG
            k8I=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qvcujpaxamuraf4neev9xcxgj40e5x54n5a8kz0xvg3fpcnl6p48xsgkyg4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDUyTHkxZyBBb3R2Um5K
            Q1VvVlplcU9HUzdwayt0bS90MHRDR1V0cGEzREtCUG9oa2pKRwpOQVAyN0w0U1J0
            aXZ4ZmhaOG9Lb3BPODZ3aHN2UXhBbHlQbWNwZEg3TUxJCi0tLSBIK0RzamsrVnUw
            UVBXekRNWWJ3WmFBbDg4cGxic0dwODc3Njh3aEpCYnNZCgCWe0S3X4dV7aquGBRK
            JiaFRDnEjeTQI9+/kIsowLZalyzLD+urh6yMJvO6R2jej/7YH2NZY80cHqqLfgz4
            qok=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dhztnm2nhdpcwsuv8uz6ss05tdx4jyfhm22dltu9l4u4fu8v3a4qs5asa7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dnFBM0FEZ3E5VE83aFJI
            K1Q4T2V3SHRobzkyWWQ1eTQ4MHpMU3J1cXc4CmlZcTdKbHZEZGpxd2Fyc3E2OFZ1
            UDU2LzVXa25MS1hoZVgyVmk4NWxxSmcKLS0tIHVhUmx6Q3RxOW9UYXN6aWdxMnlP
            SHdpS0ZoZnFycnRlejFWby9LSHVBZTQKWit6UXVi8bhI+ROA4g0L+F1Y6BZVtgC2
            QIxthbN1amrHec3wXTEOtdwjnSSx+FR3eKKQel5h0I+GEjHvxTkEfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T16:28:46Z"
    mac: ENC[AES256_GCM,data:rao1z/woc6vE1pqSZJe5+VwxO6VxfQEERR7K78IM440+CfI3Hy2BPYm/ZtpHTYcvzrSeOZ5++JJJf5hzP699kZl+7KfAVFiL9MP4IZWBouyJi5/erheDk0vn7t+SDx3rJB0WvBo1RG0nu7uqpg8YcHbFAqaa8VREIzDVqc0hRME=,iv:V+Rq8yxO37IhYPY3qTPaQTxRQLNuGs20rZuH6P7XI+M=,tag:W6IKkgmETTo2e/kQvM8osw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
