---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - barman-cloud-plugin/
  - cert-manager.yaml
  - cloudflared-tunnel-token.sops.yaml
  - cloudflared.yaml
  - cnpg.yaml
  - generic-device-plugin.yaml
  - headlamp.yaml
  - hcloud-csi-token.sops.yaml
  - hcloud-csi.yaml
  - local-path-provisioner.yaml
  - metrics-server.yaml
  - s3-backup-creds.sops.yaml
  - talos-backup.yaml
  - tailscale-operator-oauth.sops.yaml
  - tailscale-operator.yaml
  - traefik.yaml
