apiVersion: v1
kind: Secret
metadata:
    name: s3-backup-creds
    namespace: kube-system
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:hItWC6GwzhxuDwP3nuJuoqjSqeY=,iv:WTEBpcLCP9yRmJHj6xqfCMo7yndES6FfwnOt8ki3DPc=,tag:3RwjEduMbuwzFH/bqKymyg==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:PC+taQO4e0ETN+qdqBEbTnSfLLu8u9YcaOkLFtjrMLqHx3avNmp/bQ==,iv:86MwZr3hWc4z/eIoIt7rDa9vtAFVgVfgdibF9wgdE+Y=,tag:hvx8yLWwNOuT4AsrGttr6w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDJDM2Y5ZyBBNG1CZmJT
            MDUvdmd4T29iY1VObzZ4RTR5R1g2cTY3d3RYOGpyMTJnVWFPWgpoL2RWcklnWWdp
            aDJhMThNdjRaeGJIdTFHTEIzaHIxNXEwOUR2OUZzMHRjCi0tLSBvV2NSNkcvVGJk
            Umkzait1b3djclIzR1lkUmJ3YjV4bXBxK01pQnFseXh3Cg7g59QH0K5VBOiIbgr7
            TfpQLdvsNHfOJcGq1DoDdtVRHkg5fmjceXPpT7lh6S3E9CnmZ7v2fZq4dUACSM3o
            02Q=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qghympnz70sye3tx2a9yvudmmnvrq3ms7yd3gns8wz76r7k46hx0upwcu33
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDUyTHkxZyBBd2FJYlBE
            bkJXZW5CVmVWRFp6bHF6OGR5SWoveXFzblRmbjNQYjViZGpodgpsd3FPWWVRait6
            NGp5QjJCMUdKYXZzRFlaTERlcWJubmh6bFBUTVVlYkNJCi0tLSB1RFQ5c3dCNysr
            c2lzQ21sSGlhaXVLdkJ3TVRuNWwxZUM0eWxTVURuSkhzCi/NE7VyG/VzVp3wM7Vs
            7lK1UiFkpHLWf34a6VGNTIvqUlOskMawTlIJOdoJ1nkWWFC4MpPsAZS/aCpy1B1c
            Hks=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qvcujpaxamuraf4neev9xcxgj40e5x54n5a8kz0xvg3fpcnl6p48xsgkyg4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZ3lwVXNlbjUxWlNpcTZU
            NjJiMmF1dGdIQ2ZFY0wwTFdKUEhnY0NLYWdnCkJEb3BXcEw3b0VtclI5Q0ZDdld2
            M0lnT1hmbzBwamFvc3NFZ3EwYmhycDAKLS0tIG1MZ3lkT2tNcVJ1S0FIRXZQK3p5
            THUrUlhuVzVYNG9zU0NxM09NVU9NVW8KmYCGEfcWP5nG4lQF/17lLzaHsygdCW6a
            A84ptsJ9uQ4VvXpTVIgE7LsJEWbA6pWGY5AdfSIKu2+pLZUkzmAPEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhztnm2nhdpcwsuv8uz6ss05tdx4jyfhm22dltu9l4u4fu8v3a4qs5asa7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T10:28:56Z"
    mac: ENC[AES256_GCM,data:IBtnobSr6fNL1xwMcvs7TQK8CcKHJpPONInA4UrFTqYQKZZ4CJhceieC1vZPEizwIxGD2TTHJp16yL3uGSO8t0sJxVTA+LRdUHUaY+tKLFFCpBZEJKppg+t+dj4FMl1uf65LnfepSSiMSdCzjGfLvgUy4/lYA01J8Z8lAGeMn30=,iv:IBVY73QDz9AyjMUEyXArtlDe8j0rzTelnrr1wV6Sdyc=,tag:2Lcog9QXp5jBORdMjdSubQ==,type:str]
    version: 3.13.3
