apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-spending-guard
    namespace: quizmon-ops
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:xQY9BELT5Ory7j7/5KA1iurjlmfq/vOGgXDY+trqi898vp1E5NkLq7Mai6eESdvO+P9l9Mg=,iv:9ynhS9yYIx1Mp68/lR+7dTYKUG5tAQtDcSzq2NK6gtM=,tag:isUG06YmT7EpbrroLvBgzw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDJDM2Y5ZyBBK2R0dFdy
            M01EVys0bmx4M1ViR3VpZzRGSm9BQmczTTRaSDVDNDNGVGE3MgpQa0VESXRvQ2xE
            dm1OUjhtT2xlaHpHTk9VaVZncE9WWmx5NHplbHBJd2hZCi0tLSBXdFh3LzZ3Z290
            b3VKQU9iYUFOMWdWQnVCd3JmaENHR0VJdlpDQVB6VlQ4CsfxPj7UACm76DKHOQZ2
            nVsiKHZlo0J/viyCz2A7YlTO0WMw8DQZiE4Xl08qBMdGwB83/dNZFvdVGjZok5/u
            ke4=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qghympnz70sye3tx2a9yvudmmnvrq3ms7yd3gns8wz76r7k46hx0upwcu33
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDUyTHkxZyBBOHVJb3hO
            MDNnS1JyOEE2ZG9mNktSN01teWJVek9BQWdxUTN6eGZKblBhego3R3BZTEhuSWZY
            OUtHdjA5bUlSdHpBd2pSY1BHVDVhTUtObFlnLzVWNHd3Ci0tLSBra2Y5UmtjcEdT
            dUViSmlMU2JyTFZVS3IxZ0pzU1lnaS9YQVB3Wjk1R1ZrCql+4ZMvTQhjy/aeSp00
            6XPVNzXJHdOQ6+jLoOdxAfLPKfPvCXFyyz+XE9wzg9ukIo4TKGBxUUVQqKP+IGaz
            6XE=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qvcujpaxamuraf4neev9xcxgj40e5x54n5a8kz0xvg3fpcnl6p48xsgkyg4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SFVCbXJJMHBoRDVzWWhL
            d1ZubU0xNzQ4WWF5Q0xwb1FKcWNqclJwNUNFCjY0MDkwSEJNNXVrSWtsRUEwaXZt
            b0MzdWVwVjdiQldITitxZE5LcVcvOUUKLS0tIDRIVkFoWWlhSE1tZUpNdUJuaStJ
            ZmVHRENSK0NHeXlKM1VCOXQxLzZ1a1UKWwlCV5np0JFPeFB59lrLXBt/QkhOLWee
            VohxC1ya/lOHMJKm3uEDTT5pGUu8rg0XnDQuFFXR/eyiCqK5WaiYZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhztnm2nhdpcwsuv8uz6ss05tdx4jyfhm22dltu9l4u4fu8v3a4qs5asa7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-10T19:29:00Z"
    mac: ENC[AES256_GCM,data:YEOOMy5mbYzjsOu6mkrWIwvUa7Te2rn4TnBYMS4EZaCukNuPjOeHWiwQOa7S5KDRR1ywrEqrbrOX48CCYgoDxh5oxiKOE3ZTRHTnBzuCNpRfKd48vLBjfnFv8xeBUph4Q89qKnIcbRZjTdnJj+J/rKbBLKsV6bBzAR9vG516krI=,iv:vZMgDUnsIM0U7M/ZNpzo4Wuhh4M1BJQQ/ZCea2hgHvQ=,tag:Ks5cPWWD9bte4OeS0yK+jw==,type:str]
    version: 3.13.3
