---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - quizmon-db-app.sops.yaml
  - quizmon-db-source.sops.yaml
  - quizmon-db-storage.sops.yaml
  - quizmon-dns.sops.yaml
  - quizmon-backup.sops.yaml
